import type { AppConfig } from '@ai-customer-support/config';
import type { EventBus, Logger } from '@ai-customer-support/shared';
import type { AIServicePort } from '../modules/ai/application/ports/ai-service-port.js';
import type { AgentsModule } from '../modules/agents/compose-agents.js';
import type { ConversationsHttpRegistrar } from '../modules/conversations/compose-conversations.js';
import type { CustomersModule } from '../modules/customers/compose-customers.js';
import type { IdentityHttpRegistrar } from '../modules/identity/compose-identity.js';
import type { KnowledgeModule } from '../modules/knowledge/compose-knowledge.js';
import type { OnboardingModule } from '../modules/onboarding/compose-onboarding.js';
import type { OrganizationsHttpRegistrar } from '../modules/organizations/compose-organizations.js';
import type { IntegrationsModule } from '../modules/integrations/compose-integrations.js';
import type { AutomationsModule } from '../modules/automations/compose-automations.js';
import type { AnalyticsModule } from '../modules/analytics/compose-analytics.js';
import type { NotificationsModule } from '../modules/notifications/compose-notifications.js';
import type { BillingModule } from '../modules/billing/compose-billing.js';
import type { SecurityModule } from '../modules/security/compose-security.js';
import type { PlatformModule } from '../modules/platform/compose-platform.js';
import type { ObservabilityModule } from '../modules/observability/compose-observability.js';
import type { TicketsModule } from '../modules/tickets/compose-tickets.js';
import type { WidgetModule } from '../modules/widget/compose-widget.js';
import type { DatabasePort } from '../shared/application/ports/database-port.js';
import type { QueuePort } from '../shared/application/ports/queue-port.js';
import type { RedisPort } from '../shared/application/ports/redis-port.js';
import type { InfrastructureHealthChecker } from '../shared/infrastructure/health/infrastructure-health-checker.js';

export interface AppDependencies {
  readonly config: AppConfig;
  readonly logger: Logger;
  readonly database: DatabasePort;
  readonly redis: RedisPort;
  readonly eventBus: EventBus;
  readonly queue: QueuePort;
  readonly aiService: AIServicePort;
  readonly healthChecker: InfrastructureHealthChecker;
  readonly identity?: IdentityHttpRegistrar;
  readonly organizations?: OrganizationsHttpRegistrar;
  readonly customers?: CustomersModule;
  readonly tickets?: TicketsModule;
  readonly automations?: AutomationsModule;
  readonly analytics?: AnalyticsModule;
  readonly notifications?: NotificationsModule;
  readonly billing?: BillingModule;
  readonly security?: SecurityModule;
  readonly platform?: PlatformModule;
  readonly observability?: ObservabilityModule;
  readonly agents?: AgentsModule;
  readonly conversations?: ConversationsHttpRegistrar;
  readonly knowledge?: KnowledgeModule;
  readonly onboarding?: OnboardingModule;
  readonly widget?: WidgetModule;
  readonly integrations?: IntegrationsModule;
}
