export const PRESENCE_HEARTBEAT_INTERVAL_MS = 20_000;
export const PRESENCE_OFFLINE_AFTER_MS = 60_000;
export const PRESENCE_RECONNECT_GRACE_MS = 30_000;
export const MAX_WEBSOCKET_CONNECTIONS_PER_AGENT = 10;
